# Generated by Django 3.2.16 on 2023-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_photo',
            field=models.ImageField(default='/media/header-images/header-default.png', upload_to='header-images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='/media/profile-images/profile-default.png', upload_to='profile-images'),
        ),
    ]
