# Generated by Django 3.2.16 on 2023-01-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230118_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_photo',
            field=models.ImageField(default='header-default.png', upload_to='header-images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile-default.png', upload_to='profile-images'),
        ),
    ]
