from django.urls import path
from .views import *

urlpatterns = [
    ######## FEED / CREATE / REACT ########
    path('', my_feed, name="my-feed"),
    path('feed-posts-ajax/<int:num_posts>/<str:feed_type>/<str:user_profile_id>/<str:post_detail_id>/',
         feed_posts_ajax, name='feed-posts-ajax'),
    path('react-unreact-post-ajax/<str:reaction_type>/',
         react_unreact_post_ajax, name='react-unreact-post-ajax'),
    path('create-post-ajax/', create_post_ajax, name='create-post-ajax'),
    path('get-url-metadata-ajax/', get_url_metadata_ajax,
         name='get-url-metadata-ajax'),
    path('post-details/<int:pk>/', post_details, name="post-details"),
    path('post-details-ajax/', post_details_ajax, name="post-details-ajax"),
    # FEED SIDEBAR
    path('get-upcoming-birthdays-ajax/', get_upcoming_birthdays_ajax,
         name="get-upcoming-birthdays-ajax"),
    path('get-recent-events-ajax/', get_recent_events_ajax,
         name="get-recent-events-ajax"),
    path('get-people-you-may-know-ajax/', get_people_you_may_know_ajax,
         name="get-people-you-may-know-ajax"),
    ######## POST COMMENTS ########
    path('create-comment-ajax/', create_comment_ajax, name='create-comment-ajax'),
    path('get-comments-ajax/', get_comments_ajax, name="get-comments-ajax"),
    path('get-comment-count-ajax/', get_comment_count_ajax,
         name='get-comment-count-ajax'),
    path('delete-comment-ajax/', delete_comment_ajax, name='delete-comment-ajax'),
    # ######## PROFILE ########
    path('user-profile/<int:pk>/', user_profile, name="user-profile"),
    path('friend-list/', friend_list, name="friend-list"),
    path('users/', users, name="users"),  # NEW TEST
    path('users-ajax/', users_ajax, name="users-ajax"),
    path('birthdays/', birthdays, name="birthdays"),
    path('get-all-birthdays-ajax/', get_all_birthdays_ajax,
         name="get-all-birthdays-ajax"),
    path('get-my-friend-list-ajax/', get_my_friend_list_ajax,
         name="get-my-friend-list-ajax"),
    path('profile-header-photo-ajax/', profile_header_photo_ajax,
         name="profile-header-image-ajax"),
    path('update-header-photo-ajax/', update_header_photo_ajax,
         name="update-header-photo-ajax"),
    path('send-friend-request-ajax/', send_friend_request_ajax,
         name="send-friend-request-ajax"),
    path('confirm-friend-request/<int:pk>/',
         confirm_friend_request, name="confirm-friend-request"),
    path('delete-friend-request/<int:pk>/',
         delete_friend_request, name="delete-friend-request"),
    path('unfriend-user/<int:pk>/', unfriend_user, name="unfriend-user"),
    path('friend-request-pending-ajax/', friend_request_pending_ajax,
         name="friend-request-pending-ajax"),
    path('get-profile-photos-ajax/', get_profile_photos_ajax,
         name="get-profile-photos-ajax"),
    # ######## MESSAGES ########
    path('messages/', messages, name="messages"),
    path('message-thread/<int:pk>/', message_thread, name="message-thread"),
    path('get-messages-ajax/<int:friend_id>/',
         get_messages_ajax, name="get-messages-ajax"),
    path('create-message-ajax/', create_message_ajax, name="create-message-ajax"),
    path('get-new-message-ajax/', get_new_message_ajax,
         name="get-new-message-ajax"),
    # ######## EVENTS ########
    path('events/', events, name="events"),
    path('profile-event/', profile_event, name="profile-event"),
    # CALENDAR URLS:
    path('add-event', add_event, name='add-event'),
    path('update-event', update_event, name='update-event'),
    path('remove-event', remove_event, name='remove-event'),
    path('all-events', all_events, name='all-events'),
    #################### TO DO ####################
    path('create-poll/', create_poll, name="create-poll"),
    path('delete-poll/<int:pk>/', delete_poll, name="delete-poll"),
    path('my-polls/', my_polls, name="my-polls"),
    path('poll/<int:pk>/', poll, name="poll"),
    path('save-poll-entry-ajax/', save_poll_entry_ajax,
         name="save-poll-entry-ajax"),
    path('poll-results/<int:pk>/', poll_results, name="poll-results"),
    path('poll-results-ajax/', poll_results_ajax, name="poll-results-ajax"),
]
